config/routes.rb
Rails.application.routes.draw do

  root 'collections#welcome'

  resources :curators, only: [:show, :update] do
    get 'search', on: :collection, as: :search
  end

  resources :collections do
    resources :observations
    get 'search', on: :collection, as: :search
  end

  resource :inbox, :controller => 'inbox', :only => [:show,:create]

  get '/welcome', :to => 'collections#welcome'
  get '/login', :to => 'sessions#new', :as => :login
  get '/logout', :to => 'sessions#destroy', :as => :logout
  get "/auth/auth0/callback" => "auth0#callback"
  get "/auth/failure" => "auth0#failure"
  get 'collections/:id/permissions', :to => 'collections#permissions', :as => :collection_permissions
  get "/404", :to => "errors#not_found"
  get "/422", :to => "errors#unacceptable"
  get "/500", :to => "errors#internal_error"

end

app/models/Observation.rb
class Observation < ActiveRecord::Base

  belongs_to :curator
  belongs_to :collection, touch: true

  validates :curator, :collection, presence: true

end

app/models/observation.rb
class Observation < ActiveRecord::Base
  has_attached_file :image, styles: { medium: "300x300>", thumb: "200x200#" }, default_url: "/images/blank.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  validates_attachment_file_name :image, matches: [/png\Z/, /jpe?g\Z/]

  belongs_to :curator
  belongs_to :collection, touch: true

  validates :curator, :collection, presence: true
  has_one :pending_observation

  validate :at_least_one

  def approved?
    !self.pending
  end

  def has_image?
    self.image_file_name.present?
  end

  def owned_by?(user)
    self.curator_id == user.id
  end

  private

  def at_least_one
    if [self.description, self.image].reject(&:blank?).size == 0
       errors.add(:base, "Make sure you add at least a description or photo")
    end
  end

end

app/controllers/observations_controller.rb
  class ObservationsController < ApplicationController

  before_action :redirect_if_not_logged_in, only: [:new, :create, :update, :destroy]

  def index
    @observations = Observation.order(updated_at: :desc)
  end

  def new
    @collection = Collection.find(params[:collection_id])
    @observation = Observation.new
  end

  def create
    collection = Collection.find(params[:collection_id])
    observation = collection.observations.build(observation_params)
    observation.curator_id = current_user.id
    if observation.save
      if collection.user_can_add?(current_user)
        observation.pending = false
        observation.save
        flash[:notice] = "Your sighting has been added."
      else
        flash[:notice] = "Your sighting has been sent to #{collection.curator.public_name} for approval."
      end
    else
      flash[:notice] = "Make sure you add at least a description or photo."
    end
    redirect_to collection
  end

  def show
    @observation = Observation.find(params[:id])
  end

  def edit
    @collection = Collection.find(params[:collection_id])
    @observation = Observation.find(params[:id])
  end

  def update
    collection = Collection.find(params[:collection_id])
    observation = Observation.find(params[:id])
    if collection.owned_by?(current_user)
      observation.pending = false
      observation.update_attributes(observation_params)
      observation.save
    else
      flash[:error] = "You are not authorized to update sightings on this collection"
    end
    redirect_to collection_path(collection)
  end

  def destroy
    @collection = Collection.find(params[:collection_id ])
    observation = Observation.find(params[:id])
    if @collection.owned_by?(current_user) || observation.owned_by?(current_user)
      observation.destroy
    else
      flash[:error] = "You are not authorized to delete sightings on this collection"
    end
    if request.xhr?
      render 'collections/show'
    else
      redirect_to collection_path(@collection)
    end
  end

  private

  def observation_params
    params.require(:observation).permit(:description,:image, :collection_id)#.merge({curator_id: current_user.id})
  end

end

app/views/observations/_observation_show_on_collection.html.erb
<% if o.image_file_name.nil?%>
  <li class= "only-text"><span><h5><em><%= link_to o.description, collection_observation_path(@collection,o) %></span></em></li>
  <li class= "center-text"><span>Added by <%= link_to o.curator.public_name, curator_path(o.curator) %></span></h5></li>
<% else %>
  <li class= "center-pic"><%= link_to (image_tag o.image.url(:medium)), collection_observation_path(@collection,o) %></li>
  <li class= "center-text"><span><em><%= o.description %></span></em><li>
  <li class= "center-text"><span>Added by <%= link_to o.curator.public_name, curator_path(o.curator) %></span><li>
  <div class = "div-header"></div>
<% end %>

app/views/observations/edit.html.erb
<%= flash[:errors] %>
<div class="form" id="pitch_observation">
  <% if logged_in? %>
    <h2 class = "center-text">Edit Sighting</h2>
    <%= form_for @observation, url: "/collections/#{@collection.id}/observations/#{@observation.id}" do |f|%>
    <input name="_method" type="hidden" value="patch" />
      <div class="3 columns">
        <div class ="center-text">
          <div><%= f.text_area :description, placeholder: 'Description', rows: '5' %>
          </div>
        </div>
        <%= f.hidden_field :collection_id, value: @collection.id%>
        <% if @collection.user_can_add?(current_user) %>
          <div class = "center-text"><%= f.submit "Update Sighting", class: "medium button" %></div>
        <%end%>
    <% end %>
  <% else %>
    <h2><%= link_to 'Log in', login_path %> to edit this sighting.</h2>
  <% end %>
</div>

app/views/observations/index.html.erb
<ul class = "content" >
  <% @observations.each do |o| %>
    <li><%= o.description %> </li>
    <ul>
      <%= link_to (image_tag o.image.url(:thumb)), collection_observation(o.id) %>
    </ul>
  <% end %>
</ul>
<%= button_to "Add Sightings", new_collection_observation, class: "radius medium button", method: "get" %>

app/views/observations/new.html.erb
<%= flash[:errors] %>
<div class="form" id="pitch_observation">
  <% if logged_in? %>
    <h2 class = "center-text">New Sighting</h2>
    <%= form_for @observation, url: collection_observations_path(@collection),  html: { multipart: true } do |f|%>
      <div class="3 columns">
        <div class = "center-text"><%= (image_tag 'camera.png') %>
        </div>
        <div class ="center-text">
          <button class="file-upload">Add a photo
            <%= f.file_field :image %>
          </button>
          <div>
            <span id="fileName"><em>No photo added yet</em></span>
          </div>
          <div><%= f.text_area :description, placeholder: 'Description', rows: '5' %>
          </div>
        </div>
        <%= f.hidden_field :collection_id, value: @collection.id%>
          <% if @collection.user_can_add?(current_user) %>
            <div class = "center-text"><%= f.submit "Add Sighting", class: "medium button" %></div>
          <% else %>
            <div class = "center-text" id="pitch_to_collection"><%= f.submit "Pitch to #{@collection.curator.public_name}", class: "medium button" %></div>
          <%end%>
    <% end %>
  <% else %>
    <h2><%= link_to 'Log in', login_path %> to add a sighting.</h2>
  <% end %>
</div>

app/views/observations/show.html.erb
<div class = "div-header"></div>
  <div class = "observe-show">
    <% if @observation.image_file_name.nil?%>
      <h4 class= "only-text"><span><em><%= @observation.description %></span></em></h4>
      <div class= "center-text">
        <span>Added by <%= link_to @observation.curator.public_name, curator_path(@observation.curator) %></span>
      </div>
    <% else %>
      <div class= "center-pic"><%= image_tag @observation.image.url %></div>
      <h5 class= "center-text"><span><em><%= @observation.description %></span></em></h5>
    <%end%>
    <h6 class="subheader">Spotted at <%=@observation.created_at.strftime("%a, %d %b %Y %H:%M:%S")%> by <%= @observation.curator.public_name %></h6>
    <div class = "div-header"></div>
    <% if logged_in? %>
      <% if belongs_to_current_user?(@observation) || belongs_to_current_user?(@observation.collection) %>
        <div class = "center-text">
          <button data-dropdown="drop" aria-controls="drop" aria-expanded="false" class="small secondary radius button dropdown">Options</button><br>
          <ul id="drop" data-dropdown-content class="f-dropdown" role="menu" aria-hidden="false" tabindex="-1">
            <li><%= link_to 'Edit', edit_collection_observation_path(@observation.collection_id, @observation), :method => :get %></li>
            <li id="delete_observation" data-collection="<%= @observation.collection_id %>" ><%= link_to 'Delete', collection_observation_path(@observation.collection_id, @observation), :method => :delete%></li>
          </ul>
        </div>
      <%end%>
    <%end%>
  </div>
</div>