config/routes.rb
Rails.application.routes.draw do

  root 'collections#welcome'

  resources :curators, only: [:show, :update] do
    get 'search', on: :collection, as: :search
  end

  resources :collections do
    resources :observations
    get 'search', on: :collection, as: :search
  end

  resource :inbox, :controller => 'inbox', :only => [:show,:create]

  get '/welcome', :to => 'collections#welcome'
  get '/login', :to => 'sessions#new', :as => :login
  get '/logout', :to => 'sessions#destroy', :as => :logout
  get "/auth/auth0/callback" => "auth0#callback"
  get "/auth/failure" => "auth0#failure"
  get 'collections/:id/permissions', :to => 'collections#permissions', :as => :collection_permissions
  get "/404", :to => "errors#not_found"
  get "/422", :to => "errors#unacceptable"
  get "/500", :to => "errors#internal_error"

end

app/models/Curator.rb
class Curator < ActiveRecord::Base
  has_many :collections
  has_many :observations

  validates :username, presence: true

end

app/models/curator.rb
class Curator < ActiveRecord::Base
  include PgSearch
  pg_search_scope :search_curator, :against => {
    :name => 'A', :username => 'B' },
    :using => {
      :tsearch => {:dictionary => "english"}
    }

  has_attached_file :avatar,
    styles: {
      :thumb => "100x100#",
      :small  => "150x150>",
      :medium => "200x200" },
      :convert_options => {
        :thumb => "-quality 75 -strip" },
    default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  validates_attachment_file_name :avatar, matches: [/png\Z/, /jpe?g\Z/]
  has_many :collections
  has_many :observations_made, :foreign_key => 'curator_id', :class_name => "Observation"
  has_many :collection_observations, :through => :collections, :source => :observations
  has_many :roles
  has_many :authorized_collections, :through => :roles, :source => :collection
  validates :name, presence: true
  # validates :username, uniqueness: true #removed due to Auth0 issues, need to fix this

  def can_add?(coll)
    Role.exists?(curator_id: self.id, collection_id: coll.id, can_add: true)
  end

  def can_read?(coll)
    Role.exists?(curator_id: self.id, collection_id: coll.id, can_read: true)
  end

  def can_update?(coll)
    Role.exists?(curator_id: self.id, collection_id: coll.id, can_update: true)
  end

  def can_invite?(coll)
    Role.exists?(curator_id: self.id, collection_id: coll.id, can_invite: true)
  end

  def admin?(coll)
    Role.exists?(curator_id: self.id, collection_id: coll.id, admin: true)
  end

  def is_user?(user)
    self.id == user.id
  end

  def has_pending_sightings?
    self.collection_observations.where(pending: true).any?
  end

  def collections_pending
    Collection.where(curator_id: self.id).joins(:observations).where(observations: {pending: true}).uniq
  end

  def public_name
    if self.username
      self.username
    else
      self.name
    end
  end
end

app/controllers/curators_controller.rb
class CuratorsController < ApplicationController

  before_action :redirect_if_not_logged_in, only: [:update]

  def show
    @curator = Curator.find(params[:id])
    @collections = @curator.collections.order(updated_at: :desc)
  end

  def search
    @curators = Curator.search_curator(params[:c])
  end

  def profile
    @user = current_user
    render "show"
  end

  def update
    @curator = Curator.find(current_user.id)
    if @curator.update_attributes(valid_params)
      redirect_to curator_path(@curator)
    else
      flash[:errors] = "Username is already taken! Please try another name."
      redirect_to curator_path(@curator)
    end
  end

  private

  def valid_params
    params.require(:curator).permit(:username)
  end
end

app/views/curators/_pending_sightings.html.erb
<h5 class = "center-text">You have pending sightings to approve in
  <% curator.collections_pending.each do |pending_collection| %>
    <% if curator.collections_pending.length == 1 %>
      <%= link_to pending_collection.title, collection_path(pending_collection)%>.
    <% else %>
      <% if curator.collections_pending.last != pending_collection %>
        <%= link_to pending_collection.title, collection_path(pending_collection)%>,
      <% else %>
        and <%= link_to pending_collection.title, collection_path(pending_collection)%>.
      <% end %>
    <% end %>
  <%end%>
</h5>

app/views/curators/_search_results.html.erb
<ul class = "content" >
  <% @curators.each do |c| %>
    <li>
      <h2><%= link_to c.public_name, curator_path(c) %></h2>
    </li>
  <% end %>
</ul>

app/views/curators/_show_stat.html.erb
<h2 class = "center-text"><%= @curator.public_name %></h2>
<div class = "collection-description">
  <div class= "center-text">
    <ul class="accordion" data-accordion>
      <li class="accordion-navigation">
      <a href="#panel1a">About</a>
      <div id="panel1a" class="content">
        <p>Owns <%=stat_view_helper(@curator.collections.count, "collection")%></p>
        <p>Contributed <%= stat_view_helper(@curator.observations_made.count, "sighting")%></p>
        <p>Joined on <%= @curator.created_at.strftime("%b %d, %Y")%></p>
      </div>
    </ul>
</div>

app/views/curators/_username_form.html.erb
<%= form_for @curator do |f|%>
  <div class="row">
    <div class="3 columns">
      <%= f.text_field :username, placeholder: 'e.g. SpotterMcGee' %>
    </div>
  </div>
  <div class = "center-text"><%= f.submit "update username", class: "small secondary button" %>
  </div>
<% end %>

app/views/curators/search.html.erb
<div>
  <% if @curators.empty? %>
    <h2>No results found for '<%= "#{params[:c]}" %>'</h2>
  <% else %>
    <h2><%= "#{pluralize(@curators.size, 'result')} for '#{params[:c]}'" %></h2>
    <%= render partial: 'curators/search_results', curators: @curators, as: :curator %>
  <% end %>
</div>

app/views/curators/show.html.erb
<%= flash[:errors] %>

<%= render partial: 'curators/show_stat', locals: {curator: @curator} %>

<div class = "div-header"></div>

  <% if logged_in? %>
    <% if @curator.is_user?(current_user) %>
        <% if @curator.username %>
          <h4 class = "center-text">username: <%= @curator.username %>
          </h4>
          <%= render partial: 'curators/username_form', locals: { curator: @curator } %>
        <% else %>
          <h6 class = "center-text">give yourself a username:
          </h6>
          <%= render partial: 'curators/username_form', locals: { curator: @curator } %>
        <% end %>
        <% if @curator.has_pending_sightings? %>
          <%= render partial: 'pending_sightings', locals: { curator: @curator } %>
        <% end %>
    <% end %>
    <%= render partial: 'collections/show_all_profile', locals: { collections: @collections, member: true } %>
  <% else %>
    <%= render partial: 'collections/show_all_profile', locals: { collections: @collections, member: false } %>
  <% end %>