config/routes.rb
Rails.application.routes.draw do

  root 'collections#welcome'

  resources :curators, only: [:show, :update] do
    get 'search', on: :collection, as: :search
  end

  resources :collections do
    resources :observations
    get 'search', on: :collection, as: :search
  end

  resource :inbox, :controller => 'inbox', :only => [:show,:create]

  get '/welcome', :to => 'collections#welcome'
  get '/login', :to => 'sessions#new', :as => :login
  get '/logout', :to => 'sessions#destroy', :as => :logout
  get "/auth/auth0/callback" => "auth0#callback"
  get "/auth/failure" => "auth0#failure"
  get 'collections/:id/permissions', :to => 'collections#permissions', :as => :collection_permissions
  get "/404", :to => "errors#not_found"
  get "/422", :to => "errors#unacceptable"
  get "/500", :to => "errors#internal_error"

end

app/views/layouts/_header.html.erb
<div class="fixed">
  <nav class="top-bar" data-topbar role="navigation">
    <ul class="title-area">
      <li class="name">
        <h1><%= link_to 'Trainspotter', root_path %>
        </h1>
      </li>
      <li class="divider"></li>
      <li class="toggle-topbar menu-icon">
        <a href="#"><span>Menu</span></a>
      </li>
    </ul>
    <section class="top-bar-section">
      <!-- Right Nav Section -->
      <ul class="right">
        <% if logged_in? %>
          <% if current_user.has_pending_sightings? %>
            <li><%= link_to 'You have pending sightings to approve!', curator_path(current_user) %></li>
          <% end %>
          <li class="has-dropdown">
            <a href="#"><%= current_user.public_name%></a>
            <ul class="dropdown">
              <li><%= link_to 'Profile', curator_path(current_user) %></li>
              <li><%= link_to 'Log out', logout_path %></li>
            </ul>
          </li>
        <% end%>
      </ul>
      <!-- Left Nav Section -->
      <ul class="left">
        <% if logged_in? %>
          <li><%= link_to 'Make', new_collection_path %></li>
        <%else%>
          <li><%= link_to 'Login', login_path %></li>
        <% end%>
        <li><%= link_to 'Browse', collections_path %></li>
        <li class="has-form">
          <div class="row collapse">
            <div class="large-8 small-9 columns">
              <%= form_tag(search_collections_path, method: "get", enforce_utf8: false) do %>
                <%= text_field_tag(:c, "", placeholder: "Search Collections") %>
            </div>
            <div class="large-4 small-3 columns">
                <%= button_tag "Go", name: nil, class: "small secondary button", type: "submit" %>
              <% end %>
            </div>
          </div>
        </li>
      </ul>
    </section>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Trainspotter" %></title>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= stylesheet_link_tag    "application", media: 'all'  %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link href='https://fonts.googleapis.com/css?family=Fredoka+One' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Cutive+Mono' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto+Mono' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Belgrano' rel='stylesheet' type='text/css'>
  </head>
  <body>
    <%= render partial: 'layouts/header' %>
    <%= yield %>
  </body>
  <footer>
  </footer>
</html>